version: 2
updates:
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "artpar"
    assignees:
      - "artpar"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"